version: '3.8'

services:
  redis:
    image: redis:7
    container_name: upaguru_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - upaguru-net

volumes:
  redisdata:

networks:
  upaguru-net:
    driver: bridge
