version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: upaguru_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-upaguru}
    volumes:
      - mongodbdata:/data/db
    networks:
      - upaguru-net

volumes:
  mongodbdata:

networks:
  upaguru-net:
    driver: bridge
