version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: upaguru_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-upaguru}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - upaguru-net

volumes:
  pgdata:

networks:
  upaguru-net:
    driver: bridge
